# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = ["ALL"]

ignore = [
    "ANN101",  # Missing type annotation for {name} in method
    "ANN102",  # Missing type annotation for {name} in classmethod
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D107",    # Missing docstring in __init__
    "D202",    # No blank lines allowed after function docstring
    "D203",    # 1 blank line required before class docstring
    "D213",    # Multi-line docstring summary should start at the second line
    "D404",    # First word of the docstring should not be This
    "D406",    # Section name should end with a newline
    "D407",    # Section name underlining
    "D411",    # Missing blank line before section
    "E501",    # line too long
    "E731",    # do not assign a lambda expression, use a def
    "EM101",   # Exception must not use a string literal
    "EM102",   # Exception must not use an f-string literal
    "FBT001",  # Boolean positional arg in function definition
    "FBT002",  # Boolean default value in function definition
    "FIX002",  # Line contains TODO
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
    "S101",    # Use of assert detected
    "TD002",   # Missing author in TODO
    "TD003",   # Missing issue link on the line following this TODO
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.pydocstyle]
convention = "pep257"

[lint.pylint]
max-args = 10
max-branches = 25
max-returns = 15
max-statements = 100

[lint.per-file-ignores]
"tests/**" = ["S101"] # Allow assert in tests
